baseURL = 'https://blog.funkyme.farm/'
languageCode = 'en-us'
title = 'My Funky Hugo Site'

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 6 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
show_reading_time = true

[module]
[[module.imports]]
  path = 'github.com/theNewDynamic/gohugo-theme-ananke'

[languages]
  [languages.en]
    title = "Funky blog"
    weight = 1
    contentDir = "content/en"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = "/images/logo.png"
  description = "Using open source tech & community sourced. Maybe."
  facebook = ""
  twitter = "https://twitter.com/bahelit"
  instagram = ""
  youtube = ""
  github = "https://github.com/bahelit"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/michael-salmons-81748930/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-navy"
  featured_image = "/images/sundayRiver1View.jpg"
  recent_posts_number = 2